# Generated by Django 4.2 on 2024-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_address_user_phone_user_profile_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('invester', 'Invester')], default='invester', max_length=20),
        ),
    ]
