# Generated by Django 4.2 on 2024-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_account_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
