# Generated by Django 4.2 on 2024-05-09 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_networkmodel'),
        ('account', '0004_alter_user_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('coin_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.cointypemodel')),
                ('network_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.networkmodel')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='coin_amount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.coinmodel'),
        ),
    ]
