# Generated by Django 4.2 on 2024-05-08 16:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0003_networkmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('screenshot', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('coin_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.cointypemodel')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('network_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.networkmodel')),
            ],
        ),
    ]
