# Generated by Django 4.2 on 2024-05-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_coinmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinModel',
        ),
    ]
