# Generated by Django 4.2 on 2024-05-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_coinmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
