# Generated by Django 4.2 on 2024-05-04 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(default=None)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
