# Generated by Django 4.2 on 2024-05-08 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_cointypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('qrcode', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('link_name', models.CharField(max_length=20)),
                ('link_address', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
